version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0
  cypress: cypress-io/cypress@2.2.0

jobs:
  format-code:
    docker:
      - image: cimg/node:16.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a5:0c:71:4b:ba:ef:6b:c4:6e:a2:68:13:b3:85:75:4f"
      - checkout
      - run:
          name: Npm config
          command: npm config set legacy-peer-deps true
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Format code
          command: npm run format || echo ""
      - run:
          name: Configure git
          command: |
            git config user.email "ready-ci-bot@ready.com"
            git config user.name "CircleCI Job"
      - run:
          name: Commit changes
          command: |
            git commit -am "Format code [skip ci]" || 
            echo "No changes to commit"
      - run:
          name: Push changes
          command: git push origin $CIRCLE_BRANCH

  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Npm config
          command: npm config set legacy-peer-deps true
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      #- run:
      #    name: Run tests
      #    command: npm run test
      #- codecov/upload:
      #    token: CODECOV_TOKEN

workflows:
  workflow:
    jobs:
      - format-code
      - build-and-test:
          requires:
            - format-code
      - cypress/run:
          requires:
            - build-and-test
          install-command: npm i --legacy-peer-deps
          record: true
          store_artifacts: true
          attach-workspace: false
