version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0
  cypress: cypress-io/cypress@2.2.0

parameters:
  run_build:
    type: boolean
    default: false

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build
          command: npm run build
      #- run:
      #    name: Run tests
      #    command: npm run test
      - codecov/upload:
          token: CODECOV_TOKEN

workflows:
  version: 2

  on-pull-request-open:
    when: << pipeline.parameters.run_build >>
    jobs:
      - build-and-test
      - cypress/run:
          record: true
          store_artifacts: true
          attach-workspace: false
