export enum ErrorCode {
  EmailNotFoundException = "EmailNotFoundException",
  UnknownException = "UnknownException",
  InvalidDataException = "InvalidDataException",
  InvalidApiResponseException = "InvalidApiResponseException",
  InvalidIdException = "InvalidIdException",
  NotFoundException = "NotFoundException",
  ProductNotFoundException = "ProductNotFoundException",
  BuffetNotFoundException = "BuffetNotFoundException",
  InternalServerErrorException = "InternalServerErrorException",
  ServiceUnavailableException = "ServiceUnavailableException",
  InvalidLoginException = "InvalidLoginException",
  PasswordNotSetException = "PasswordNotSetException",
  InactiveUserException = "InactiveUserException",
  EmailDuplicateException = "EmailDuplicateException",
  ForbiddenException = "ForbiddenException",
}
